table 'Measures - Air'
	lineageTag: 3e9e0886-b975-4e70-8b7b-d5487f4abcf5

	measure 'Air Shipment Count' =
			
			COUNTROWS(Fact_Air_Shipments)
			
			// Total count of air freight shipment transactions in the current filter context
		formatString: 0
		lineageTag: 87565747-ed7c-4ab9-b30d-fb0d2c60b9d4

	measure 'Total Actual Weight (KG)' =
			
			SUM(Fact_Air_Shipments[ActualWeightKG])
			
			// Total cargo weight across all air shipments
		formatString: #,0.00 KG
		lineageTag: cc744908-ad49-4b08-913d-4a77b9e63f96

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Total Volume (CBM)' =
			
			SUM(Fact_Air_Shipments[VolumeCBM])
			
			// Total cargo volume (cubic metres) across all air shipments
		formatString: #,0.0000 m³
		lineageTag: d717af38-70cd-42c7-a9ef-671b9ff1300d

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Total Chargeable Weight' =
			
			VAR SelectedModes = VALUES( Dim_Carriers[ModeOfTransport] )
			RETURN
			    IF(
			        "Air" IN SelectedModes,
			        SUMX(
			            Fact_Air_Shipments,
			            MAX( Fact_Air_Shipments[ActualWeightKG], Fact_Air_Shipments[VolumeCBM] * 167 )
			        ),
			        BLANK()
			    )
			
			// Air cargo is billed on whichever is greater: actual weight or volumetric weight (1 CBM = 167 KG IATA standard density ratio)
		formatString: #,0.00 kg
		lineageTag: 1c9ddf6a-64cd-4f7c-86a6-8d31ecfd9a67

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Total Air Revenue' = ```
			
			SUMX(
			    Fact_Air_Shipments,
			    VAR ChargeableWeight = 
			        MAX(Fact_Air_Shipments[ActualWeightKG], Fact_Air_Shipments[VolumeCBM] * 167)
			    RETURN
			    ChargeableWeight * Fact_Air_Shipments[ClientSellRatePerKG]
			)
			
			// Total client-billed revenue from air freight, calculated as chargeable weight × client sell rate per shipment.
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c95bb97d-6751-4820-91ec-975e772e661e

	measure 'Total Air Cost' = ```
			
			SUMX(
			    Fact_Air_Shipments,
			    VAR ChargeableWeight = 
			        MAX(Fact_Air_Shipments[ActualWeightKG], Fact_Air_Shipments[VolumeCBM] * 167)
			    RETURN
			    ChargeableWeight * Fact_Air_Shipments[AirlineBuyRatePerKG]
			)
			
			// Total airline procurement cost, calculated as chargeable weight × airline buy rate per shipment.
			```
		lineageTag: bf108533-3340-448d-8e51-0a5454d0ab3c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Air Gross Profit' =
			
			[Total Air Revenue] - [Total Air Cost]
		formatString: "R"#,0.00;-"R"#,0.00;"R"#,0.00
		lineageTag: 1e8d321e-0f92-42b5-9957-347cc39e7d6a

		annotation PBI_FormatHint = {"currencyCulture":"en-ZA"}

	measure 'Air Gross Profit Margin %' =
			
			DIVIDE(
			    [Total Air Revenue] - [Total Air Cost],
			    [Total Air Revenue],
			    0
			)
			
			// The percentage of revenue retained after airline procurement costs. Measures the effectiveness of buy/sell rate negotiation
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 70fe5103-5be6-4147-9736-659469687119

	measure 'Avg Buy Rate Per KG' =
			
			AVERAGE(Fact_Air_Shipments[AirlineBuyRatePerKG])
			
			// Average airline procurement rate per kilogram across all air shipments.
		formatString: "R"#,0.###############;-"R"#,0.###############;"R"#,0.###############
		lineageTag: 7f5f5e57-3a26-4e28-bd1d-8f1479147eb2

		annotation PBI_FormatHint = {"currencyCulture":"en-ZA"}

	measure 'Avg Sell Rate Per KG' =
			
			AVERAGE(Fact_Air_Shipments[AirlineBuyRatePerKG])
			
			// Average client-billed rate per kilogram across all air shipments.
		formatString: "R"#,0.###############;-"R"#,0.###############;"R"#,0.###############
		lineageTag: fd69f657-4cc7-454b-8759-b867da1ca776

		annotation PBI_FormatHint = {"currencyCulture":"en-ZA"}

	partition 'Measures - Air' = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				  #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

